"""Agent management commands."""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Annotated

import typer

from ..core.config import dominion_path, project_root
from ..core.formatters import error, info, output, table
from ..core.readers import read_toml, read_toml_glob, read_toml_optional

app = typer.Typer(help="Agent configuration management")

SPECIALIZED_ROLES = [
    "frontend-engineer", "api-designer", "database-engineer",
    "devops", "cloud-engineer", "technical-writer",
    "observability-engineer", "release-manager", "innovation-engineer",
]

UNIVERSAL_CLI_COMMANDS = ["state position", "state resume", "data get", "data set"]


def _load_cli_spec() -> dict[str, str]:
    """Load cli-spec.toml and return a dict of command name -> description."""
    spec_path = dominion_path("specs", "cli-spec.toml")
    data = read_toml_optional(spec_path)
    if not data:
        return {}
    return {cmd["name"]: cmd.get("description", "") for cmd in data.get("commands", [])}


def _normalize_cli_commands(tools: dict) -> list[str]:
    """Extract CLI command list from tools dict, handling flat and nested formats."""
    cli = tools.get("cli")
    if cli is None:
        return []
    if isinstance(cli, list):
        return cli
    if isinstance(cli, dict):
        return cli.get("commands", [])
    return []


def _expand_cli_commands(
    commands: list[str], spec: dict[str, str],
) -> list[tuple[str, str]]:
    """Expand group prefixes and resolve descriptions from cli-spec.toml.

    Returns sorted list of (name, description) tuples.
    """
    result: dict[str, str] = {}
    for cmd in commands:
        name = cmd.removeprefix("dominion-cli ").strip()
        name = name.removesuffix(" *").strip()

        # Exact match
        if name in spec:
            result[name] = spec[name]
            continue

        # Group prefix — expand to all matching leaf commands
        prefix = name + " "
        matches = {k: v for k, v in spec.items() if k.startswith(prefix)}
        if matches:
            result.update(matches)
        else:
            # Graceful degradation — include with empty description
            result[name] = ""

    return sorted(result.items())


@app.command(name="list")
def list_agents(
    available: Annotated[bool, typer.Option("--available", help="Show all roles including inactive")] = False,
    json: Annotated[bool, typer.Option("--json", help="Output as JSON")] = False,
) -> None:
    """List active agents with role, model, and purpose."""
    agents = read_toml_glob(dominion_path("agents"))

    columns = ["Agent", "Model", "Purpose"]
    rows = []
    active_roles = set()

    for a in agents:
        role = a.get("role", {}).get("name", a.get("_file", ""))
        model = a.get("model", {}).get("name", "")
        purpose = a.get("role", {}).get("purpose", "")
        rows.append([role, model, purpose])
        active_roles.add(a.get("_file", ""))

    if available:
        for spec_role in SPECIALIZED_ROLES:
            if spec_role not in active_roles:
                rows.append([spec_role, "—", "(available, not active)"])

    table("Agents", columns, rows, json)


@app.command()
def show(
    role: Annotated[str, typer.Argument(help="Agent role name")],
    json: Annotated[bool, typer.Option("--json", help="Output as JSON")] = False,
) -> None:
    """Show full config for one agent."""
    path = dominion_path("agents", f"{role}.toml")
    if not path.exists():
        # Try with dashes/underscores variants
        agents_dir = dominion_path("agents")
        available = [f.stem for f in agents_dir.glob("*.toml")] if agents_dir.is_dir() else []
        error(f"Agent '{role}' not found. Available: {', '.join(available)}")
        raise SystemExit(1)

    data = read_toml(path)
    # Remove internal keys
    data.pop("_file", None)
    output(data, json)


@app.command()
def generate() -> None:
    """Regenerate AGENTS.md and .claude/agents/*.md from agent TOMLs."""
    agents = read_toml_glob(dominion_path("agents"))
    cli_spec = _load_cli_spec()
    root = project_root()
    claude_agents_dir = root / ".claude" / "agents"
    claude_agents_dir.mkdir(parents=True, exist_ok=True)

    # Build AGENTS.md
    lines = [
        "<!-- Auto-generated by Dominion. Do not edit manually. -->",
        f"# Agents — {datetime.now(timezone.utc).strftime('%Y-%m-%d')}",
        "",
        "## Active Roster",
        "",
        "| Agent | Model | Purpose |",
        "| --- | --- | --- |",
    ]

    for a in agents:
        role_name = a.get("role", {}).get("name", a.get("_file", ""))
        model = a.get("model", {}).get("name", "")
        purpose = a.get("role", {}).get("purpose", "")
        lines.append(f"| {role_name} | {model} | {purpose} |")

    # File ownership
    lines.extend(["", "## File Ownership", ""])
    for a in agents:
        role_name = a.get("role", {}).get("name", a.get("_file", ""))
        ownership = a.get("governance", {}).get("file_ownership", [])
        if ownership:
            lines.append(f"- **{role_name}**: {', '.join(ownership)}")

    # Governance summary
    lines.extend(["", "## Governance", ""])
    for a in agents:
        role_name = a.get("role", {}).get("name", a.get("_file", ""))
        hard_stops = a.get("governance", {}).get("hard_stops", [])
        if hard_stops:
            lines.append(f"- **{role_name}** hard stops: {'; '.join(hard_stops)}")

    # Spawning reference
    lines.extend(["", "## Spawning Reference", ""])
    for a in agents:
        role_name = a.get("role", {}).get("name", a.get("_file", ""))
        slug = a.get("_file", role_name.lower().replace(" ", "-"))
        produces = a.get("workflow", {}).get("produces", [])
        mcp_tools = a.get("tools", {}).get("mcp", [])
        cli_cmds = _normalize_cli_commands(a.get("tools", {}))
        expanded_cmds = _expand_cli_commands(cli_cmds, cli_spec)
        lines.append(f"### {role_name}")
        lines.append(f"- Invoke: `/dominion:agents spawn {slug}`")
        if mcp_tools:
            lines.append(f"- MCP tools: {', '.join(mcp_tools)}")
        if expanded_cmds:
            cmd_names = [f"`dominion-cli {n}`" for n, _ in expanded_cmds]
            lines.append(f"- CLI: {', '.join(cmd_names)}")
        if produces:
            lines.append(f"- Produces: {', '.join(produces)}")
        lines.append("")

    agents_md = root / "AGENTS.md"
    agents_md.write_text("\n".join(lines) + "\n")
    info(f"Generated {agents_md}")

    # Generate per-agent .claude/agents/*.md
    for a in agents:
        slug = a.get("_file", "")
        role_data = a.get("role", {})
        role_name = role_data.get("name", slug)
        purpose = role_data.get("purpose", "")
        model = a.get("model", {}).get("name", "")

        md_lines = [
            f"<!-- Dominion-managed agent: {slug} -->",
            f"# {role_name}",
            "",
            f"**Purpose:** {purpose}",
            f"**Model:** {model}",
            "",
        ]

        # MCP Tools section
        tools = a.get("tools", {})
        mcp_tools = tools.get("mcp", [])
        if mcp_tools:
            md_lines.append("## Tools")
            md_lines.append(f"- MCP: {', '.join(mcp_tools)}")
            md_lines.append("")

        # CLI Commands Available section
        cli_commands = _normalize_cli_commands(tools)
        expanded = _expand_cli_commands(cli_commands, cli_spec)
        # Inject universal commands (deduplicated)
        existing_names = {name for name, _ in expanded}
        for ucmd in UNIVERSAL_CLI_COMMANDS:
            if ucmd not in existing_names:
                desc = cli_spec.get(ucmd, "")
                expanded.append((ucmd, desc))
        expanded.sort()

        md_lines.append("## CLI Commands Available")
        md_lines.append("")
        md_lines.append(
            "NEVER edit `.dominion/` TOML files directly. "
            "All reads and writes go through these commands."
        )
        md_lines.append("")
        for cmd_name, cmd_desc in expanded:
            if cmd_desc:
                md_lines.append(f"- `dominion-cli {cmd_name}` — {cmd_desc}")
            else:
                md_lines.append(f"- `dominion-cli {cmd_name}`")
        md_lines.append("")

        # Governance section
        gov = a.get("governance", {})
        if gov:
            md_lines.append("## Governance")
            if gov.get("file_ownership"):
                md_lines.append(f"- File ownership: {', '.join(gov['file_ownership'])}")
            if gov.get("hard_stops"):
                md_lines.append(f"- Hard stops: {'; '.join(gov['hard_stops'])}")
            if gov.get("architectural_decisions"):
                md_lines.append(f"- Architectural decisions: {gov['architectural_decisions']}")
            md_lines.append("")

        # Methodology section
        meth = a.get("methodology", {})
        if meth:
            md_lines.append("## Methodology")
            if meth.get("mode"):
                md_lines.append(f"- Mode: {meth['mode']}")

            phases = meth.get("phases", [])
            if phases:
                md_lines.append("")
                md_lines.append("### Phases")
                md_lines.append("| Phase | Purpose | Key Activities |")
                md_lines.append("| --- | --- | --- |")
                for ph in phases:
                    name = ph.get("name", "")
                    purpose_val = ph.get("purpose", "")
                    activities = ", ".join(ph.get("key_activities", []))
                    md_lines.append(f"| {name} | {purpose_val} | {activities} |")

            methods = meth.get("methods", [])
            if methods:
                md_lines.append("")
                md_lines.append("### Methods")
                md_lines.append("| Method | Source | Purpose |")
                md_lines.append("| --- | --- | --- |")
                for m in methods:
                    md_lines.append(f"| {m.get('name', '')} | {m.get('source', '')} | {m.get('purpose', '')} |")

            tool_routing = meth.get("tool_routing", [])
            if tool_routing:
                md_lines.append("")
                md_lines.append("### Tool Routing")
                md_lines.append("| Task | Tool | Reason |")
                md_lines.append("| --- | --- | --- |")
                for tr in tool_routing:
                    md_lines.append(f"| {tr.get('task', '')} | {tr.get('tool', '')} | {tr.get('reason', '')} |")

            evidence = meth.get("evidence_grades", [])
            if evidence:
                md_lines.append("")
                md_lines.append("### Evidence Grades")
                for eg in evidence:
                    md_lines.append(f"- **{eg.get('grade', '')}**: {eg.get('description', '')}")

            protocols = meth.get("specialist_protocols", [])
            if protocols:
                md_lines.append("")
                md_lines.append("### Specialist Protocols")
                md_lines.append("| When | Protocol | Description |")
                md_lines.append("| --- | --- | --- |")
                for sp in protocols:
                    md_lines.append(
                        f"| {sp.get('when', '')} | {sp.get('protocol', '')} | {sp.get('description', '')} |"
                    )

            md_lines.append("")

        # Research lens
        lens = a.get("research_lens", {})
        if lens:
            md_lines.append("## Research Lens")
            for key, val in lens.items():
                if isinstance(val, list):
                    md_lines.append(f"- {key}: {', '.join(str(v) for v in val)}")
                else:
                    md_lines.append(f"- {key}: {val}")
            md_lines.append("")

        # Workflow
        wf = a.get("workflow", {})
        if wf:
            md_lines.append("## Workflow")
            if wf.get("produces"):
                md_lines.append(f"- Produces: {', '.join(wf['produces'])}")
            if wf.get("commit_style"):
                md_lines.append(f"- Commit style: {wf['commit_style']}")
            md_lines.append("")

        agent_md = claude_agents_dir / f"{slug}.md"
        agent_md.write_text("\n".join(md_lines) + "\n")

    info(f"Generated {len(agents)} agent files in {claude_agents_dir}")
