"""Documentation generation commands."""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Annotated

import typer

from ..core.config import dominion_path, project_root
from ..core.formatters import info, output
from ..core.readers import read_toml, read_toml_glob, read_toml_optional

app = typer.Typer(help="Documentation management")


@app.command()
def generate() -> None:
    """Generate DOMINION.md project overview at project root."""
    dom = read_toml(dominion_path("dominion.toml"))
    roadmap = read_toml_optional(dominion_path("roadmap.toml"))
    agents = read_toml_glob(dominion_path("agents"))
    root = project_root()

    project = dom.get("project", {})
    direction = dom.get("direction", {})
    governance = dom.get("governance", {})

    lines = [
        "<!-- Auto-generated by Dominion. Do not edit manually. -->",
        f"# {project.get('name', 'Project')}",
        "",
        f"**Vision:** {project.get('vision', '')}",
        f"**Direction:** {direction.get('mode', 'maintain')}",
        f"**Generated:** {datetime.now(timezone.utc).strftime('%Y-%m-%d')}",
        "",
    ]

    # Roadmap
    if roadmap:
        lines.append("## Roadmap")
        lines.append("")
        phases = roadmap.get("phases", [])
        if phases:
            lines.append("| Phase | Title | Status |")
            lines.append("| --- | --- | --- |")
            for p in phases:
                lines.append(
                    f"| {p.get('number', '')} | {p.get('title', '')} | {p.get('status', 'upcoming')} |"
                )
        lines.append("")

    # Agents
    if agents:
        lines.append("## Agents")
        lines.append("")
        lines.append("| Agent | Model | Purpose |")
        lines.append("| --- | --- | --- |")
        for a in agents:
            role = a.get("role", {})
            lines.append(
                f"| {role.get('name', a.get('_file', ''))} "
                f"| {a.get('model', {}).get('name', '')} "
                f"| {role.get('purpose', '')} |"
            )
        lines.append("")

    # Governance
    if governance:
        lines.append("## Governance")
        lines.append("")
        for key, val in governance.items():
            if isinstance(val, list):
                lines.append(f"- **{key}:** {', '.join(str(v) for v in val)}")
            elif isinstance(val, dict):
                lines.append(f"- **{key}:**")
                for k2, v2 in val.items():
                    lines.append(f"  - {k2}: {v2}")
            else:
                lines.append(f"- **{key}:** {val}")
        lines.append("")

    dominion_md = root / "DOMINION.md"
    dominion_md.write_text("\n".join(lines) + "\n")
    info(f"Generated {dominion_md}")


@app.command()
def show(
    json: Annotated[bool, typer.Option("--json", help="Output as JSON")] = False,
) -> None:
    """Display current DOMINION.md contents."""
    root = project_root()
    dominion_md = root / "DOMINION.md"

    if not dominion_md.exists():
        info("No DOMINION.md found. Run doc generate first.")
        return

    content = dominion_md.read_text()
    if json:
        output({"content": content}, json_mode=True)
        return

    info(content)
