"""Release management commands."""

from __future__ import annotations

from typing import Annotated

import typer

from ..core.config import dominion_path
from ..core.formatters import error, info, output
from ..core.readers import read_toml, read_toml_optional

app = typer.Typer(help="Release management")


@app.command()
def prepare() -> None:
    """Generate changelog and PR synopsis from commit history."""
    spec_path = dominion_path("specs", "release-spec.toml")
    spec = read_toml(spec_path)

    release_dir = dominion_path("release")
    release_dir.mkdir(parents=True, exist_ok=True)

    changelog_path = release_dir / "changelog-draft.md"
    synopsis_path = release_dir / "synopsis-draft.md"

    # Initialize draft files
    changelog_path.write_text(
        "# Changelog Draft\n\n"
        "<!-- Auto-generated by dominion-cli release prepare -->\n"
        "<!-- Fill in from git log since last tag -->\n\n"
        "## Features\n\n## Fixes\n\n## Refactoring\n"
    )
    synopsis_path.write_text(
        "# PR Synopsis Draft\n\n"
        "<!-- Auto-generated by dominion-cli release prepare -->\n"
        "<!-- Summarize key changes for the pull request -->\n\n"
    )

    info("Release drafts ready. Review in .dominion/release/")
    info("Note: Git log analysis should be performed by the agent using gh/git commands.")


@app.command()
def publish(
    level: Annotated[str, typer.Option("--level", help="Version bump level: major, minor, patch")],
) -> None:
    """Execute full release ceremony."""
    valid_levels = ("major", "minor", "patch")
    if level not in valid_levels:
        error(f"Invalid level '{level}'. Must be one of: {', '.join(valid_levels)}")
        raise SystemExit(1)

    release_dir = dominion_path("release")
    if not release_dir.is_dir():
        error("No release drafts found. Run 'release prepare' first.")
        raise SystemExit(1)

    changelog = release_dir / "changelog-draft.md"
    synopsis = release_dir / "synopsis-draft.md"
    if not changelog.exists() or not synopsis.exists():
        error("Missing draft files. Run 'release prepare' first.")
        raise SystemExit(1)

    spec = read_toml(dominion_path("specs", "release-spec.toml"))

    info(f"Release ceremony initiated (bump: {level}).")
    info("Steps to complete:")
    info("  1. Verify drafts reviewed")
    info(f"  2. Bump version ({level})")
    info("  3. Build artifacts (if configured)")
    info("  4. Publish to registries")
    info("  5. Create PR and tag")
    info("  6. Create GitHub release")
    info("Note: Actual git/gh operations should be performed by the agent.")


@app.command(name="status")
def release_status(
    json: Annotated[bool, typer.Option("--json", help="Output as JSON")] = False,
) -> None:
    """Show current release spec configuration and version info."""
    spec_path = dominion_path("specs", "release-spec.toml")
    spec = read_toml(spec_path)

    versioning = spec.get("versioning", {})
    registries = spec.get("registries", {})

    data = {
        "spec_version": spec.get("meta", {}).get("version", ""),
        "version_source": versioning.get("source", ""),
        "registries": list(registries.keys()) if isinstance(registries, dict) else [],
    }

    if json:
        output(data, json_mode=True)
        return

    info(f"  Release spec: {data['spec_version']}")
    info(f"  Version source: {data['version_source']}")
    info(f"  Registries: {', '.join(data['registries']) if data['registries'] else 'none'}")
    info("  Note: Run 'release prepare' to analyze git history for version/tag info.")
